### PR TITLE
Add border around avatar to identify their cursor color

### LINKED ISSUE #338: [UX] Avatar with border
Can we make a border to the avatars with the colour of the cursor? (this allow you to identify each person easier).

### PR DESCRIPTION
**Pull request by jasonrudolph**
Closes #338

Depends on https://github.com/atom/teletype-client/pull/61

---

### Description of the Change

This pull request implements the design shown in https://github.com/atom/teletype/issues/338#issuecomment-371802426.

In the screenshot below, we see the addition of colored borders around some avatars. When a participant's cursor appears in the current editor, the avatar will now have a border with a color that matches the user's cursor color.

screenshot

### Verification Process

- [x] Border shown when another collaborator is typing in the same editor
- [x] Border not shown when another collaborator is typing in a different editor
- [x] Border appears again when collaborator navigates to the editor you're currently viewing and begins typing or selecting
- [x] Border not shown when another collaborator is viewing a non-portal item (e.g., the settings view)
- [x] Border not shown when another collaborator has a retracted tether
- [x] Up to 15 sites can have unique cursor colors

### TODO

- [x] Implement preliminary functionality
- [x] Reduce duplication in CSS re: site colors (e.g., [cursor color for site 6](https://github.com/atom/teletype/blob/a6c293a5fd57987d095f3260b65c730b7519ec84/styles/teletype.less#L348-L350) vs. [avatar border color for site 6](https://github.com/atom/teletype/blob/a6c293a5fd57987d095f3260b65c730b7519ec84/styles/teletype.less#L441-L443))
- [x] Update [tests](https://github.com/atom/teletype/blob/a1f6eeaf102c57236008e383c8e5ba7b225fd06b/test/site-positions-component.test.js#L36-L71) to exercise this new behavior
- [x] Define and execute verification process

### CODE REVIEW

**Comment by jasonrudolph** [comment]
@simurai: I took a first pass at the CSS for this pull request, but I'd love to get your eyes on it. Would you mind taking a look to see if there's anything we should change? Feel free to push any recommended changes to this branch. 

One thing in particular that I'd like help with is the way the link icon is rendered in relation to the border. It's difficult to explain in words, but hopefully the screenshot below gives you an idea of the issue:

screen_shot_2018-04-17_at_18_57_34_pm

Is there a way that we can improve that?

**Comment by simurai** [comment]
> the way the link icon is rendered in relation to the border. 

Moved the icon a bit to better cover the site border:

image

**Comment by jasonrudolph** [comment]
Thanks for those updates, @simurai. They look great! :zap:

**Comment by jasonrudolph** [comment]
Some light stress testing...

screenshot

**Pull request merged**
