### PR TITLE
Save buffer on the host when attempting to save it on the guest

### PR DESCRIPTION
**Pull request by as-cii**
Closes https://github.com/atom/teletype/issues/240

This pull request uses the APIs introduced in https://github.com/atom/teletype-client/pull/45 to:

* Perform a save request when attempting to save a remote buffer on the guest (e5aa4c0).
* Honor the save request on the host by flushing changes to disk. Requests to save in-memory buffers are ignored by the host. (0edbe49)

### Verification

* Open a new Atom instance and share a portal.
* Open a new Atom instance and join the previously shared portal.
* Edit the buffer on the guest portal and save.
* Observe saves being relayed to the host buffer.

/cc: @nathansobo @jasonrudolph

### CODE REVIEW

**Comment by jasonrudolph** [comment]
@as-cii: Thanks for putting this together! :zap:

Can I talk you into describing a [verification process](https://github.com/atom/teletype/blame/9b8a3cde53e246184ba260034a80ca750627a6dd/PULL_REQUEST_TEMPLATE.md#L28-L40) for these changes?

**Comment by jasonrudolph** [comment]
I tried out these changes locally in dev mode, and I'm seeing a weird interaction with the popular [file-icons package](https://atom.io/packages/file-icons):

1. Host opens `a.txt` in their workspace
1. Host shares portal
1. Guest joins portal and sees editor for `a.txt`
1. Host closes `a.txt`
1. Guest sees exception:

    ```
    Uncaught (in promise) TypeError: Cannot assign empty path
        at File.setPath (~/.atom/packages/file-icons/node_modules/atom-fs/lib/resource.js:232)
        at bufferDisposables.CompositeDisposable.buffer.onDidChangePath.to (~/.atom/packages/file-icons/node_modules/atom-fs/lib/file.js:185)
        at Function.module.exports.Emitter.simpleDispatch (~/github/atom/node_modules/event-kit/lib/emitter.js:25)
        at Emitter.module.exports.Emitter.emit (~/github/atom/node_modules/event-kit/lib/emitter.js:141)
        at BufferBinding.restoreOriginalBufferMethods (~/github/teletype/lib/buffer-binding.js:63)
        at BufferBinding.dispose (~/github/teletype/lib/buffer-binding.js:22)
        at bufferDestroySubscription.buffer.onDidDestroy (~/github/teletype/lib/buffer-binding.js:40)
        at Function.module.exports.Emitter.simpleDispatch (~/github/atom/node_modules/event-kit/lib/emitter.js:25)
        at Emitter.module.exports.Emitter.emit (~/github/atom/node_modules/event-kit/lib/emitter.js:141)
        at TextBuffer.module.exports.TextBuffer.destroy (~/github/atom/node_modules/text-buffer/lib/text-buffer.js:1503)
        at TextBuffer.module.exports.TextBuffer.release (~/github/atom/node_modules/text-buffer/lib/text-buffer.js:1553)
        at TextEditor.destroy (~/github/atom/src/text-editor.js:593)
        at lastEditorProxyChangePromise.lastEditorProxyChangePromise.then (~/github/teletype/lib/guest-portal-binding.js:86)
    ```

I don't observe this exception when using the current Teletype release (0.3.0).

**Comment by as-cii** [comment]
> Do you see those errors when you run the tests locally?

I am seeing those errors on master as well. I will look into them shortly.

> I tried out these changes locally in dev mode, and I'm seeing a weird interaction with the popular file-icons package:

I ended up going back to monkey-patching everything in `EditorBinding`, as there seem to be issues when clearing the path of a buffer and emitting a `did-change-path` event after doing so. I've added some verification steps in the body of this pull request and I will go ahead and merge these changes into master as soon as we get a green build.

**Comment by kieranklaassen** [comment]
Thanks, this is great!

**Pull request merged**
