### PR TITLE
[Code Submission] RFC-002: Sync Buffer Path Changes from Host To Guest

### PR DESCRIPTION
**Pull request by CaptainJohnyAppleSeed**
### Description of the Change

This is the changes to the **Teletype** package mentioned in [RFC-002 Tracking](atom/teletype/352).

Please see [RFC-002](https://github.com/atom/teletype/issues/352) for details about the change.

### Verification Process
We have made 2 tests in Buffer-Binding, we are open to making more tests if needed.

### Applicable Issues
Original Issue: [#147](atom/teletype/147)

### CODE REVIEW

**Comment by CaptainJohnyAppleSeed** [comment]
Saw the following as an error from Travis CI. 
`The command "./build-package.sh" exited with 1.`
We will look into this, to see where our submission has erred.

**Comment by 50Wliu** [comment]
Look at the errors above that line.  They are all linting errors.

**Comment by CaptainJohnyAppleSeed** [comment]
Just noticed them and am starting on correcting the style issues 😄

**Comment by jasonrudolph** [comment]
:wave: Hi @CaptainJohnyAppleSeed, Hi @odoyle71: Thanks for this pull request. :bow:

How would you feel about updating the implementation to use the approach described in https://github.com/atom/teletype-client/pull/55#issuecomment-376234864?

**Comment by CaptainJohnyAppleSeed** [comment]
@jasonrudolph Thanks for your patience, we've finished making the changes as noted in atom/teletype-client#55 We believe that everything is working well together, if you could give it a look at your leisure. Thanks!

**Comment by CaptainJohnyAppleSeed** [comment]
@jasonrudolph @as-cii Looks great, thanks for working on this!

**Comment by jasonrudolph** [comment]
@CaptainJohnyAppleSeed @odoyle71: Thank you for this contribution. :bow::smile:

We pushed up a few refinements to the code. Each individual commit aims to make a single refinement, so if you're interested in seeing what we changed, please have a look. 🙂 

I'll merge this shortly, and I hope to publish these changes in a new release within the next week or so.

Thanks again! 🍰

**Pull request merged**
